title: 一是不怕 二是乐观
description: 忍耐
url: "https://eveningZhang.github.io"
baseurl: ""

markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

author:
  name: denNyxp
  email: eveningjone@163.com

github_username: eveningZhang

header_pages:
  - about.md

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
