source "https://rubygems.org"

# GitHub Pages 会自动带上兼容的 Jekyll 版本
gem "github-pages", "232", group: :jekyll_plugins

# 主题
gem "minima", "~> 2.5"

# 插件
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows / JRuby 时区支持
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Windows 下如果自动刷新有问题再保留；Jekyll Windows 文档推荐 0.2.0
gem "wdm", "~> 0.2.0", install_if: Gem.win_platform?

# JRuby 兼容
gem "http_parser.rb", "~> 0.6.0", platforms: [:jruby]